name: Daily Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node generate.js

      - name: Commit update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add today.json
          git commit -m "Daily update" || echo "No changes"
          git push
